### ISSUE TITLE
code-coverage executable arguments

### ISSUE THREAD

**Issue by panchagil** [StableCoder/cmake-scripts#1]
I'm using your code-coverage script and is working great! (than you)

I wanted to know if it is possible to pass arguments to the executable when running the coverage? I'm using this for test-coverage and I want to, for example, see the coverage of a specific test. I would like to do something like this

```
ccov-unit_tests -- catch2_args
```

Thanks!

**Comment by sergeyklay** [comment]
@StableCoder Any thoughts on this

**Comment by StableCoder** [comment]
There's no easy way I can think of doing this, since how the tests are called are platform/generator dependent.

I might be able to allow for generating multiple coverage targets per library/executable, such as the base `ccov-unit_tests` and `ccov-unit_tests-args` where the arguments are passed into CMake at configuration/generation time.

I'll try to make something, but I can't affect the behaviour at the call point, I'm pretty sure.

**Comment by StableCoder** [comment]
Alright, I've got something that works for this.
When setting a target_code_coverage, there's two new arguments

- COVERAGE_TARGET_NAME which takes a single string, which is used to dictate the name of the coverage target, so rather than being forces to have ccov-$(TARGET_NAME}, now it can be customized, and thus have multiple coverage targets for the same executable, where the new ones are ccov-${COVERAGE_TARGET_NAME} instead.
- ARGS, which can take in any number of arguments, which is then appended to the executable call when the coverage target is called.
