### ISSUE TITLE
Build fails with `lcov`

### ISSUE THREAD

**Issue by mscofield0** [StableCoder/cmake-scripts#27]
I am on Ubuntu 20.04 and this happens when I try to run:

```bash
cmake -GNinja ... -DCMAKE_BUILD_TYPE=Debug -Stest -Bbuild(test
```

```bash
CMake Error at .../build/test/_deps/cmake-scripts-src/code-coverage.cmake:253 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "GreeterTests".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * CMakeLists.txt:42 (target_link_libraries)

Call Stack (most recent call first):
  CMakeLists.txt:68 (target_code_coverage)
```

The relevant CMake code is:
```cmake
target_code_coverage(Greeter)
target_code_coverage(GreeterTests AUTO)
```

It works fine with `llvm-cov` so there's something specific about `lcov` I would assume.

**Comment by StableCoder** [comment]
This looks to be an issue with the signature of `GreeterTests`

It looks like, wherever you've used target_link_libraries it hasn't been using the PRIVATE/INTERFACE/PUBLIC keywords, ala:
```
target_link_libraries(GreeterTests *library*)
```
rather than something like
```
target_link_libraries(GreeterTests PRIVATE *library*)
```
and the issue is that CMake enforces them all to be one style or the other. The code-coverage code is assuming that, unless it is specified as PUBLIC or INTERFACE at the call point, that it should be PRIVATE by default.

The reason it's only here is because only the GCC variant needs to link to an external library `gcov`. LLVM doesn't need to link into any external library.

Unfortunately, I can't see a way to programmatically determine if a keyword has been used to previous calls, so I'm going to keep the current behavior as-is.

To fix your case specifically, just add the appropriate keywords at the other callpoints to `target_link_libraries` for `GreeterTests`

**Comment by mscofield0** [comment]
With `target_link_libraries(GreeterTests PRIVATE doctest::doctest Greeter::Greeter)`:

```cmake
code-coverage.cmake:447 (add_dependencies):
  The dependency target "ccov-report-GreeterTests" of target "ccov-report"
  does not exist.
  ```
