### ISSUE TITLE
Question: Why doesn't the `link-time-optimization.cmake` script work with GCC?

### ISSUE THREAD

**Issue by mscofield0** [StableCoder/cmake-scripts#28]

**Comment by StableCoder** [comment]
This is because my script is using the builtin LTO support in CMake behind the scenes currently, and that only supports Clang's thin(incremental) LTO capability.

GCC does not have this, and has full monolithic LTO (like Clang) or their own version of WHOPR (WHOle Program optimizeR). I haven't gotten around to implementing it for GCC, since the thin LTO works on both Clang and MSVC, covering my use cases.
