### ISSUE TITLE
Question: Long Link Time when using coverage

### ISSUE THREAD

**Issue by kevin--** [StableCoder/cmake-scripts#48]
First off thanks for your code-coverage.cmake! We have been using it successfully.

Our application is structured as a "core library" with our normal executable and a Catch2 test harness executable
```
                 /----> app
                /
libapp-core.a -+
                \
                 \----> app-test
```

This works great, however we need to ensure that all of `libapp-core.a` gets linked into the test executable, otherwise our coverage stats are only for the code that has tests written, rather than all of the objects in `libapp-core`. So we use `-force_load`

```
include( code-coverage )
target_code_coverage( app-core )
target_code_coverage( app-test EXCLUDE lib/* test/* "${CMAKE_BINARY_DIR}/*")
target_link_options( app-test PRIVATE -force_load $<TARGET_FILE:app-core> )
```

In practice, when we run this on our CI system, the linker step can take a very long time to execute with this flag, resulting in timeouts.

Do you have any idea on how we might generate coverage for the entire static library without incurring such a penalty on the linker?

Currently on Xcode Apple LLVM version 14.0.3 (clang-1403.0.22.14.1) but this has been an issue on an off for several years

**Comment by StableCoder** [comment]
Hi there.

I think so. I think I can extend the ability to directly load objects from shared to static libraries so that it does it without your `-force_load`.

I have a WIP commit in another branch (https://github.com/StableCoder/cmake-scripts/tree/static-object-coverage-test) here (https://github.com/StableCoder/cmake-scripts/commit/b54df3b27a8d613f7d322c3e73071ec8db29a43a).

So with this you should be able to do like this instead:
```cmake
include( code-coverage )
target_code_coverage( app-core )
target_code_coverage( app-test EXCLUDE lib/* test/* "${CMAKE_BINARY_DIR}/*" FULL_OBJECTS app-core)

# Can now do normal instead of special link
target_link_libraries(app-test PRIVATE app-core)
```

Can you give it a quick try and confirm it works in your environment? If it does, I'll do a bit more refinement to formalize it and add it properly.

Thanks.

**Comment by StableCoder** [comment]
Alright, it's part of the 24.04 release now.

https://github.com/StableCoder/cmake-scripts/releases/tag/24.04
