### ISSUE TITLE
Sanitizer compilation test fails with Xcode generator.

### ISSUE THREAD

**Issue by jdumas** [StableCoder/cmake-scripts#49]
Hi. Running CMake with the Xcode generator seems to fails the compilation for Address sanitizer on macOS:

```bash
❯ cmake .. -G "Xcode" -DUSE_SANITIZER=Address
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode13.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode13.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Testing with Address sanitizer
CMake Error at /Users/jedumas/external/git/cmake-scripts/sanitizers.cmake:77 (message):
  Address sanitizer not available for
  /Applications/Xcode13.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)


-- Configuring incomplete, errors occurred!
```

Furthermore it looks like the `-fsanitize=address` flag should also be passed to linker options. I would generally recommend setting global options via `add_compile_options()` and `add_link_options()` rather than mucking around with `CMAKE_CXX_FLAGS` or `CMAKE_EXE_LINKER_FLAGS` directly though, but that's probably a separate issue.

**Comment by StableCoder** [comment]
The sanitizers script has been updated to make use of the `add_compile_options()` and `add_link_options()` instead of the original variable manipulation.

As for the error message from Xcode13. That error occurs if, during the configuration step CMake is unable to compile a simple program with the provided flags, in this case `-fsanitize=address`, which would likely indicate that Xcode13 does not support the sanitizer via that method. It may be a case that there is no address sanitizer with that version, or like earlier version of MSVC's address sanitizer, it was enabled via different non-standard flags.

**Comment by jdumas** [comment]
Interestingly, with the latest changes, the command above works with the Xcode generator, and it properly detects that ASan is available. Looks like it paid off to modernize the `sanitizer.cmake` script :)

**Comment by StableCoder** [comment]
That is fantastic news, enjoy.
