### ISSUE TITLE
Sanitizers - how to change from default?

### ISSUE THREAD

**Issue by vadi2** [StableCoder/cmake-scripts#53]
Thanks for the update to the sanitizers cmake this summer!

If I set the default to be `add_sanitizer_support(address)` in my cmake to be a default for all builds, how can then I adjust which sanitisers should be used on an individual basis? Is the intention that you'd then modify the cmake file, or can you pass an environment variable which will override this?

**Comment by StableCoder** [comment]
There are numerous ways to adjust the active sanitizer(s), all of which depends on what is passed to `add_sanitizer_support`.

So for example, to use grab it from a set environment variable such as `MUDLET_SANITIZER` you could do:
```cmake
set_sanitizer_options(address DEFAULT -fno-omit-frame-pointer)
set_sanitizer_options(thread DEFAULT -fno-omit-frame-pointer)
...

if($ENV{MUDLET_SANITIZER})
  add_sanitizer_support($ENV{MUDLET_SANITIZER})
else()
  add_sanitizer_support(address)
endif()
```

or, make it a CMake option variable which can be set with the default `address`:
```cmake
set_sanitizer_options(address DEFAULT -fno-omit-frame-pointer)
set_sanitizer_options(thread DEFAULT -fno-omit-frame-pointer)
...

set(MUDLET_SANITIZER
      "address"
      CACHE STRING
      "Compile with sanitizers. Available sanitizers are: address, thread, etc")

add_sanitizer_support(${MUDLET_SANITIZER})
```
but it can be changed at configure time via cmake/ccmake, like
```sh
cmake -S src -B build -D MUDLET_SANITIZER=thread
```

This change was all in service for the ability of projects to now declare more/various custom sanitizer combinations, instead of being limited to the original set I came up with in 2018:
```cmake
set_sanitizer_options(address DEFAULT)

set_sanitizer_options(
    address-omitted-frame 
    SANITIZER address 
    DEFAULT -fno-omit-frame-pointer)

set_sanitizer_options(
    address-use-return
    SANITIZER address
    DEFAULT -fsanitize-address-use-after-return=always)

...etc
```

**Comment by vadi2** [comment]
Works perfect. Thanks :+1:
